apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-login
  template:
    metadata:
      labels:
        app: nginx-login
    spec:
      containers:
      - name: nginx-login
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-login-service
spec:
  type: NodePort
  selector:
    app: nginx-login
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
